run_id: robotwin
run_root_dir: results/Checkpoints/robotwin
seed: 2026
trackers:
- wandb
wandb_entity: null
wandb_project: finetune-RoboTwin
is_debug: false
framework:
  name: LaWAM
  qwenvl:
    base_vlm: results/Checkpoints/qwen3_weights
  action_model:
    future_action_window_size: 49
    past_action_window_size: 0
    action_horizon: 50
    lam_ckpt_path: latent_action_model/logs/dino_large_vae/lam_release/checkpoints/pytorch_model.pt
    lam_yaml_path: latent_action_model/logs/dino_large_vae/lam_release/dino_large_vae.yaml
    num_action_queries: 8
    flow_action_num_queries: 8
    perceptual_weight: 0.1
    latent_action_placeholder_token: <ACT_PH>
    flow_only_mode: false
    enable_flow_h_t1_scheduled_sampling: false
    flow_h_t1_pred_prob_start: 0.0
    flow_h_t1_pred_prob_end: 1.0
    flow_h_t1_pred_ramp_steps: 20000
    detach_future_feature: true
    future_prediction: true
    enable_loss_distill: true
    lam_encoder_distill_weight: 0.1
    repeated_diffusion_steps: 2
    flow_cfg:
      action_dim: 32
      state_dim: 32
      use_state: false
      vlm_dim: 2048
      hidden_dim: 1024
      attention_heads: 16
      num_layers: 16
      interleave_self_attention: true
      use_alternate_vldit: true
      attend_text_every_n_blocks: 2
      cfg_drop_prob: 0.0
      cfg_guidance_scale: 1.0
      num_inference_steps: 10
      num_timestep_buckets: 1000
      horizon_sec: 1.2
      noise_beta_alpha: 1.5
      noise_beta_beta: 1.0
      noise_s: 0.999
      use_action_positional_embeddings: true
datasets:
  vla_data:
    data_root_dir: dataset
    data_mix: robotwin_merged
    image_resolution: 256
    per_device_batch_size: 16
    video_backend: pyav
    num_frames: 2
    enable_primary_video_aug: false
    enable_primary_random_resized_crop: false
    sec_chunk: 1.2
    enable_video_frame_cache: false
trainer:
  max_train_steps: 100000
  num_warmup_steps: 2000
  save_interval: 100000
  eval_interval: 1000
  eval_batches: 20
  learning_rate:
    base: 0.0001
    action_model:
      lr: 0.0001
      modules:
      - policy_backend.flow
    world_model:
      lr: 0.0003
      modules:
      - policy_backend.lam.decoder
    vlm:
      lr: 0.0001
      modules:
      - policy_backend.vlm
  lr_scheduler_type: cosine_with_min_lr
  scheduler_specific_kwargs:
    min_lr: 5.0e-07
  freeze:
    freeze_vision_backbone: false
    freeze_llm_backbone: false
    keep_llm_first_n_layers: 16
    freeze_last_llm_layer: true
    freeze_embedding: true
    unfreeze_vision_merger: true
    unfreeze_llm_last_n_layers: -1
    unfreeze_lam_decoder: true
  logging_frequency: 200
  gradient_clipping: 1.0
  gradient_accumulation_steps: 2
  ddp_find_unused_parameters: false
  optimizer:
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    weight_decay: 1.0e-08
  pretrained_checkpoint: results/Checkpoints/pretrain/lawam_pretrain/final_model/pytorch_model.pt
  load_pretrained_policy_flow: true
  use_pretrained_dataset_statistics: false
