"""Build simulator-grounded preserve masks for Cosmos scene variation.

The masks are white where RGB should be preserved by Cosmos guided generation
(robot + manipulated object + goal object), and black elsewhere.  They are
generated by replaying saved LIBERO MuJoCo states through LIBERO's native
``SegmentationRenderEnv`` so the mask is aligned with the original demo views.

This script is intentionally independent from the training pipeline.  It is a
small data-preparation utility for the Pipeline-v3 scene-variance smoke test.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--suite", default="libero_spatial")
    parser.add_argument("--task-id", type=int, default=0)
    parser.add_argument("--demo-index", type=int, default=0)
    parser.add_argument("--window", type=int, default=25)
    parser.add_argument("--fps", type=float, default=20.0)
    parser.add_argument("--dilate", type=int, default=3)
    parser.add_argument(
        "--preserve-name",
        action="append",
        default=["black_bowl", "plate"],
        help="Case-insensitive substring of an instance name to preserve. Repeatable.",
    )
    return parser.parse_args()


def _add_libero_source(root: Path) -> None:
    source = root / ".venv" / "src" / "libero"
    if not source.is_dir():
        raise FileNotFoundError(f"LIBERO source tree is missing: {source}")
    if str(source) not in sys.path:
        sys.path.insert(0, str(source))


def _dataset_path(root: Path, suite: str, task_id: int) -> tuple[Path, Path, str]:
    from libero.libero import benchmark

    suites = benchmark.get_benchmark_dict()
    if suite not in suites:
        raise ValueError(f"Unknown LIBERO suite {suite!r}")
    task_suite = suites[suite]()
    if task_id < 0 or task_id >= task_suite.n_tasks:
        raise ValueError(f"task-id {task_id} outside [0,{task_suite.n_tasks})")
    task = task_suite.get_task(task_id)
    demo_rel = Path(task_suite.get_task_demonstration(task_id))
    demo_candidates = (
        root / ".venv" / "src" / "libero" / "libero" / "datasets" / demo_rel,
        root / ".venv" / "datasets" / demo_rel,
        root / demo_rel,
    )
    demo_path = next((path for path in demo_candidates if path.is_file()), None)
    if demo_path is None:
        raise FileNotFoundError(f"LIBERO demonstration is missing: {demo_rel}")

    bddl_path = (
        root
        / ".venv"
        / "src"
        / "libero"
        / "libero"
        / "libero"
        / "bddl_files"
        / task.problem_folder
        / task.bddl_file
    )
    if not bddl_path.is_file():
        raise FileNotFoundError(f"LIBERO BDDL is missing: {bddl_path}")
    return demo_path, bddl_path, str(task.language)


def _grasp_window(gripper: np.ndarray, length: int, window: int) -> tuple[int, int]:
    width = np.abs(gripper).sum(axis=1)
    closed = np.clip((0.06 - width) / (0.06 - 0.02), 0.0, 1.0)
    candidates = np.flatnonzero(closed >= 0.5)
    center = int(candidates[0]) if len(candidates) else length // 2
    size = min(int(window), int(length))
    start = max(0, min(center - size // 2, length - size))
    return start, start + size


def _write_video(path: Path, frames: list[np.ndarray], fps: float, *, gray: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    height, width = frames[0].shape[:2]
    writer = cv2.VideoWriter(
        str(path), cv2.VideoWriter_fourcc(*"mp4v"), float(fps), (width, height), not gray
    )
    if not writer.isOpened():
        raise RuntimeError(f"Could not create video: {path}")
    for frame in frames:
        writer.write(frame)
    writer.release()


def _instance_mapping(env) -> dict[int, str]:
    """Return observation segmentation value -> LIBERO instance name."""

    names = list(env.env.model.instances_to_ids.keys())
    # robosuite's instance segmentation sensor maps raw geom IDs to the index
    # in ``instances_to_ids`` and then adds one; 0 is background.
    return {index + 1: str(name) for index, name in enumerate(names)}


def _select_ids(mapping: dict[int, str], substrings: list[str]) -> dict[str, list[int]]:
    lowered = [value.lower() for value in substrings]
    selected: dict[str, list[int]] = {value: [] for value in substrings}
    selected["robot"] = []
    for seg_id, name in mapping.items():
        lower_name = name.lower()
        if lower_name in {"panda0", "mountedpanda0", "rethinkmount0", "pandagripper0"}:
            selected["robot"].append(seg_id)
        for original, needle in zip(substrings, lowered):
            if needle in lower_name:
                selected[original].append(seg_id)
    return selected


def _mask_from_seg(seg: np.ndarray, ids: set[int], dilate: int) -> np.ndarray:
    values = np.asarray(seg).squeeze()
    mask = np.isin(values, list(ids)).astype(np.uint8) * 255
    if dilate > 0:
        size = 2 * int(dilate) + 1
        kernel = np.ones((size, size), dtype=np.uint8)
        mask = cv2.dilate(mask, kernel, iterations=1)
    return mask


def main() -> None:
    args = parse_args()
    root = Path.cwd().resolve()
    _add_libero_source(root)

    import h5py
    from libero.libero.envs import SegmentationRenderEnv
    import libero.libero.utils.utils as libero_utils

    demo_path, bddl_path, language = _dataset_path(root, args.suite, args.task_id)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    with h5py.File(demo_path, "r") as handle:
        names = sorted(handle["data"].keys())
        if not names:
            raise ValueError(f"No demonstrations in {demo_path}")
        demo_name = names[int(args.demo_index) % len(names)]
        demo = handle["data"][demo_name]
        states = np.asarray(demo["states"], dtype=np.float64)
        obs = demo["obs"]
        source_agent = np.asarray(obs["agentview_rgb"], dtype=np.uint8)
        source_wrist = np.asarray(obs["eye_in_hand_rgb"], dtype=np.uint8)
        gripper = np.asarray(obs["gripper_states"], dtype=np.float32)
        model_xml = demo.attrs.get("model_file")
        if isinstance(model_xml, bytes):
            model_xml = model_xml.decode("utf-8")
        if model_xml:
            model_xml = libero_utils.postprocess_model_xml(str(model_xml), {})

    length = min(len(states), len(source_agent), len(source_wrist), len(gripper))
    start, stop = _grasp_window(gripper[:length], length, args.window)
    states = states[start:stop]
    source_agent = source_agent[start:stop]
    source_wrist = source_wrist[start:stop]

    env = SegmentationRenderEnv(
        bddl_file_name=str(bddl_path),
        camera_segmentations="instance",
        camera_names=["agentview", "robot0_eye_in_hand"],
        camera_heights=128,
        camera_widths=128,
    )
    try:
        env.reset()
        # Do not load the archived model XML by default. Official LIBERO demos
        # can contain absolute asset paths from the collection machine. The
        # current BDDL environment has the same task model topology; replaying
        # the saved flattened state is sufficient for segmentation and avoids
        # stale asset-root failures. RGB MAE below verifies alignment.

        mapping = _instance_mapping(env)
        selected = _select_ids(mapping, list(args.preserve_name))
        selected_ids = {value for values in selected.values() for value in values}
        if not selected["robot"]:
            raise RuntimeError(f"Could not find robot IDs in instance mapping: {mapping}")
        missing = [name for name in args.preserve_name if not selected.get(name)]
        if missing:
            raise RuntimeError(
                f"Could not match preserve instance names {missing}; mapping={mapping}"
            )

        agent_masks: list[np.ndarray] = []
        wrist_masks: list[np.ndarray] = []
        replay_agent: list[np.ndarray] = []
        replay_wrist: list[np.ndarray] = []
        rgb_mae: dict[str, list[float]] = {"agentview": [], "wrist": []}

        for index, state in enumerate(states):
            rendered = env.regenerate_obs_from_state(state)
            agent_seg = rendered["agentview_segmentation_instance"]
            wrist_seg = rendered["robot0_eye_in_hand_segmentation_instance"]
            agent_mask = _mask_from_seg(agent_seg, selected_ids, args.dilate)
            wrist_mask = _mask_from_seg(wrist_seg, selected_ids, args.dilate)
            agent_masks.append(agent_mask)
            wrist_masks.append(wrist_mask)

            agent_rgb = np.asarray(rendered["agentview_image"], dtype=np.uint8)
            wrist_rgb = np.asarray(rendered["robot0_eye_in_hand_image"], dtype=np.uint8)
            replay_agent.append(cv2.cvtColor(agent_rgb, cv2.COLOR_RGB2BGR))
            replay_wrist.append(cv2.cvtColor(wrist_rgb, cv2.COLOR_RGB2BGR))
            rgb_mae["agentview"].append(
                float(np.abs(agent_rgb.astype(np.float32) - source_agent[index].astype(np.float32)).mean())
            )
            rgb_mae["wrist"].append(
                float(np.abs(wrist_rgb.astype(np.float32) - source_wrist[index].astype(np.float32)).mean())
            )

        _write_video(args.output_dir / "agentview_preserve_mask.mp4", agent_masks, args.fps, gray=True)
        _write_video(args.output_dir / "wrist_preserve_mask.mp4", wrist_masks, args.fps, gray=True)
        _write_video(
            args.output_dir / "agentview_source.mp4",
            [cv2.cvtColor(frame, cv2.COLOR_RGB2BGR) for frame in source_agent],
            args.fps,
        )
        _write_video(
            args.output_dir / "wrist_source.mp4",
            [cv2.cvtColor(frame, cv2.COLOR_RGB2BGR) for frame in source_wrist],
            args.fps,
        )
        _write_video(args.output_dir / "agentview_replay_rgb.mp4", replay_agent, args.fps)
        _write_video(args.output_dir / "wrist_replay_rgb.mp4", replay_wrist, args.fps)

        for camera, masks in (("agentview", agent_masks), ("wrist", wrist_masks)):
            frame_dir = args.output_dir / f"{camera}_preserve_mask_frames"
            frame_dir.mkdir(parents=True, exist_ok=True)
            for index, mask in enumerate(masks):
                cv2.imwrite(str(frame_dir / f"{index:05d}.png"), mask)

        report = {
            "suite": args.suite,
            "task_id": int(args.task_id),
            "language": language,
            "demo_name": demo_name,
            "source": str(demo_path),
            "bddl": str(bddl_path),
            "window": {"start": int(start), "stop": int(stop), "frames": int(stop - start)},
            "preserve_name_substrings": list(args.preserve_name),
            "instance_mapping": {str(key): value for key, value in mapping.items()},
            "selected_ids": selected,
            "preserve_mask_area_ratio": {
                "agentview": [float(np.mean(mask > 0)) for mask in agent_masks],
                "wrist": [float(np.mean(mask > 0)) for mask in wrist_masks],
            },
            "replay_rgb_mae": {
                key: {
                    "mean": float(np.mean(values)),
                    "max": float(np.max(values)),
                }
                for key, values in rgb_mae.items()
            },
        }
        (args.output_dir / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(report, indent=2), flush=True)
    finally:
        env.close()


if __name__ == "__main__":
    main()
